name: Release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  release:
    name: ${{ inputs.tag }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Pull from GHCR
        uses: ./.github/actions/ghcr_pull
        with:
          tag: ${{ inputs.tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Push Images
        shell: bash
        run: |
          docker tag ${{ inputs.tag }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ inputs.tag}}:${{ github.sha }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ inputs.tag}}:${{ github.sha }}
